name: trend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.8.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.15
  get: ^4.6.6
  shared_preferences: ^2.3.4
  lottie: ^3.2.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  fluttertoast: ^8.2.10
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  image_cropper: ^8.1.0
  insta_assets_picker: ^3.1.0
  image: ^4.3.0
  change_app_package_name: ^1.4.0
  get_storage: ^2.1.1
  scrollable_positioned_list: ^0.3.8
  flutter_list_view: ^1.1.29
  readmore: ^3.0.0
  emoji_picker_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

  # flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
